import { Files } from '../files';
import { Paths } from '../paths';
import { FileExtension } from '../constants';
import type { WriteFileOptions } from 'node:fs';
import type { AbsolutePath, WrittenFile } from '../@types';
import type { Metafile, OutputFile, Plugin } from 'esbuild';

/**
 * Writes output files to disk, rewriting relative specifiers in JS files and setting executable permissions for entry points with shebangs.
 * @param outputFiles - Array of output files generated by esbuild.
 * @param outputs - Metafile outputs mapping from esbuild.
 * @param directory - The base directory for resolving output paths.
 * @param iifeFiles - Array of IIFE output files, if any.
 * @returns Array of written files with their relative paths and sizes.
 */
async function writeOutput(outputFiles: OutputFile[], outputs: Metafile['outputs'], directory: AbsolutePath, iifeFiles: OutputFile[] | undefined): Promise<WrittenFile[]> {
	const hasExtension = (specifier: string): boolean => {
		const hashIndex = specifier.indexOf('#');
		const queryIndex = specifier.indexOf('?');
		let suffixStart = specifier.length;

		if (hashIndex !== -1) { suffixStart = Math.min(suffixStart, hashIndex) }
		if (queryIndex !== -1) { suffixStart = Math.min(suffixStart, queryIndex) }

		const path = specifier.slice(0, suffixStart);
		const lastSlashIndex = path.lastIndexOf('/');
		const fileName = lastSlashIndex === -1 ? path : path.slice(lastSlashIndex + 1);
		return fileName.includes('.');
	};

	const entryPoints = new Set<string>();
	for (const [ outputPath, { entryPoint } ] of Object.entries(outputs)) {
		if (entryPoint && outputPath.endsWith(FileExtension.JS)) { entryPoints.add(Paths.absolute(directory, outputPath)) }
	}

	const writtenFiles: WrittenFile[] = [];
	const writeEntries: Array<{ path: AbsolutePath; data: string | NodeJS.ArrayBufferView; options?: WriteFileOptions }> = [];

	const processOutput = (file: OutputFile): void => {
		const { path, contents } = file;
		const absolutePath = Paths.absolute(directory, path);
		let data: string | NodeJS.ArrayBufferView = contents;
		let size = contents.byteLength;
		let options: WriteFileOptions | undefined;

		if (absolutePath.endsWith(FileExtension.JS)) {
			const hasRelativeSpecifierImport = outputs[path]?.imports?.some(({ path: importPath }) =>
				(importPath.startsWith('./') || importPath.startsWith('../'))
				&& !importPath.endsWith('/')
				&& !hasExtension(importPath)) ?? false;

			if (hasRelativeSpecifierImport) {
				// `OutputFile.text` is a lazily decoded getter — only touch it for files that actually need rewriting.
				const rawText = typeof file.text === 'string' ? file.text : Buffer.from(contents).toString('utf8');
				const rewritten = Files.rewriteRelativeSpecifiers(rawText);
				if (rewritten !== rawText) {
					data = rewritten;
					size = Buffer.byteLength(rewritten);
				}
			}

			if (entryPoints.has(absolutePath) && Files.hasShebang(contents)) { options = { mode: 0o755 } }
		}

		writeEntries.push({ path: absolutePath, data, options });
		writtenFiles.push({ path: Paths.relative(directory, absolutePath), size });
	};

	for (const file of outputFiles) { processOutput(file) }
	for (const file of iifeFiles ?? []) { processOutput(file) }

	await Files.writeFiles(writeEntries);

	return writtenFiles;
}

export const createWriteOutputPlugin = (directory: AbsolutePath, onWritten: (writtenFiles: WrittenFile[]) => void, iifeFiles?: OutputFile[]): Plugin => ({
	name: 'tsbuild:write-output',
	/**
	 * Sets up the plugin to write output files to disk after the build process completes.
	 * @param build The esbuild build context.
	 */
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) { return }

			const outputs = result.metafile?.outputs;
			if (outputs === undefined) { return }

			const writtenFiles = await writeOutput(result.outputFiles ?? [], outputs, directory, iifeFiles);
			onWritten(writtenFiles);
		});
	}
});
