import { Files } from '../files';
import { Paths } from '../paths';
import { FileExtension } from '../constants';
import type { Metafile, OutputFile, Plugin } from 'esbuild';
import type { AbsolutePath, WrittenFile, Mutable, SourceFile } from '../@types';

const relativeSpecifierPredicate = ({ path: importPath }: { path: string }) =>
	(importPath.startsWith('./') || importPath.startsWith('../')) && !importPath.endsWith('/') && !hasExtension(importPath);

const hasExtension = (specifier: string) => {
	const hashIndex = specifier.indexOf('#');
	const queryIndex = specifier.indexOf('?');
	let suffixStart = specifier.length;

	if (hashIndex !== -1) { suffixStart = Math.min(suffixStart, hashIndex) }
	if (queryIndex !== -1) { suffixStart = Math.min(suffixStart, queryIndex) }

	const path = specifier.slice(0, suffixStart);
	const lastSlashIndex = path.lastIndexOf('/');

	// Determines if the last segment of the path contains a dot, indicating a file extension.
	return (lastSlashIndex === -1 ? path : path.slice(lastSlashIndex + 1)).includes('.');
};

/**
 * Writes output files to disk, rewriting relative specifiers in JS files and setting executable permissions for entry points with shebangs.
 * @param outputFiles - Array of output files generated by esbuild.
 * @param outputs - Metafile outputs mapping from esbuild.
 * @param directory - The base directory for resolving output paths.
 * @param iifeFiles - Array of IIFE output files, if any.
 * @returns Array of written files with their relative paths and sizes.
 */
async function writeOutput(outputFiles: OutputFile[], outputs: Metafile['outputs'], directory: AbsolutePath, iifeFiles: OutputFile[] = []): Promise<WrittenFile[]> {
	const outputMetadata = new Map<AbsolutePath, Metafile['outputs'][string]>();
	const entryPoints = new Set<string>();

	for (const [ outputPath, metadata ] of Object.entries(outputs)) {
		const absolutePath = Paths.absolute(directory, outputPath);
		outputMetadata.set(absolutePath, metadata);

		if (metadata.entryPoint && absolutePath.endsWith(FileExtension.JS)) { entryPoints.add(absolutePath) }
	}

	const processOutput = (file: OutputFile): SourceFile => {
		const { contents } = file;
		const path = Paths.absolute(directory, file.path);
		const sourceFile: Mutable<SourceFile> = { path, data: contents, size: contents.byteLength, options: undefined };

		if (path.endsWith(FileExtension.JS)) {
			if (outputMetadata.get(path)?.imports.some(relativeSpecifierPredicate) ?? false) {
				// `OutputFile.text` is a lazily decoded getter — only touch it for files that actually need rewriting.
				const rewritten = Files.rewriteRelativeSpecifiers(file.text);
				sourceFile.data = rewritten;
				sourceFile.size = Buffer.byteLength(rewritten);
			}

			if (entryPoints.has(path) && Files.hasShebang(contents)) { sourceFile.options = { mode: 0o755 } }
		}

		return sourceFile;
	};

	const writeEntries: SourceFile[] = [];

	for (const file of outputFiles) { writeEntries.push(processOutput(file)) }

	for (const file of iifeFiles) { writeEntries.push(processOutput(file)) }

	return Files.writeFiles(directory, writeEntries);
}

export const createWriteOutputPlugin = (directory: AbsolutePath, onWritten: (writtenFiles: WrittenFile[]) => void, iifeFiles?: OutputFile[]): Plugin => ({
	name: 'tsbuild:write-output',
	/**
	 * Sets up the plugin to write output files to disk after the build process completes.
	 * @param build The esbuild build context.
	 */
	setup(build) {
		build.onEnd(async ({ outputFiles, metafile: { outputs } = {}, errors }) => {
			if (errors.length > 0 || outputs === undefined) { return }

			onWritten(await writeOutput(outputFiles ?? [], outputs, directory, iifeFiles));
		});
	}
});
